### ISSUE TITLE
`#[openapi]` should handle `#[deprecated]`

### ISSUE THREAD

**Issue by matt-phylum** [GREsau/okapi#106]
Currently, there does not appear to be any way to mark an operation as deprecated without fixing up the OpenApi document afterwards.

When using the `#[openapi]` attribute to generate documentation for a `#[deprecated]` handler,
1. A warning about using a deprecated function should not be emitted at the handler function declaration. I'm pretty sure this is coming from `#[openapi]` and not Rocket's endpoint attribute (`#[put]` in my case), but I didn't remove it to verify. In any case, we're giving meaning to the `#[deprecated]` attribute where it didn't really have one before, so if Rocket is generating this warning, okapi should probably suppress it if possible. Most likely, the warning _should_ still be generated when mounting the route and that can be left up to the user to suppress.
2. In the generated API spec, the corresponding operation should be marked as deprecated.

This behavior is consistent with schemars.

**Comment by ralpha** [comment]
Just to make sure I understand it correctly:
- If a route has `#[deprecated]` currently `#[openapi]` will generate a warning? And you want this warning to be removed? What is the exact warning?
- The route should be marked as deprecated in the spec if `#[deprecated]` is used?

And regarding the respecting of the `#[deprecated]` and reflecting it in the spec. I agree.

**Comment by matt-phylum** [comment]
The warning is emitted even if you don't mount the endpoint or otherwise use it in any way.

```rust
#![allow(unused)]

use rocket::{get, Build, Rocket};
use rocket_okapi::openapi;

#[get("/")]
#[deprecated]
fn handler_without_docs() -> &'static str {
    "ok"
}

#[openapi]
#[get("/")]
#[deprecated]
fn handler_with_docs() -> &'static str {
    "ok"
}

#[rocket::launch]
#[allow(deprecated)]
fn launch() -> Rocket<Build> {
    rocket::build()
}
```

Actually using the handler does not produce any warnings:

```rust
use rocket::{get, Build, Rocket, routes};
use rocket_okapi::openapi;

#[allow(deprecated)]
mod handlers {
    use super::*;

    #[get("/")]
    #[deprecated]
    pub fn handler_without_docs() -> &'static str {
        "ok"
    }

    #[openapi]
    #[get("/")]
    #[deprecated]
    pub fn handler_with_docs() -> &'static str {
        "ok"
    }
}

#[rocket::launch]
#[allow(deprecated)]
fn launch() -> Rocket<Build> {
    rocket::build()
        .mount("/without_docs", routes![handlers::handler_without_docs])
        .mount("/with_docs", routes![handlers::handler_with_docs])
}
```

I'm pretty sure `#[get]` is defining a type which implements something like `Into<Route>` and the warning is generated by that impl.

**Comment by ralpha** [comment]
> I'm pretty sure #[get] is defining a type which implements something like Into<Route> and the warning is generated by that impl.
Yeah the macro is using it internally somewhere. Strange that the handler thing changes that.

But other then `#[openapi(deprecated = true)]` I don't see and immediate solution.

**Comment by matt-phylum** [comment]
It might be possible for the `#[openapi]` attribute to remove the `#[deprecated]` attribute so Rocket doesn't see it, or wrap the Rocket-generated code in a module, but neither of those sound good, if they're even possible. I haven't tried to do anything like that in an attribute macro before.

Maybe Rocket can be convinced to change this as the current behavior doesn't seem useful at all.

I like both options. `#[openapi(deprecated = true)]` is good to have even if later `#[deprecated]` becomes an option, I think.

**Comment by ralpha** [comment]
Thanks for following up on this issue and resolving it! Very nicely done! :star_struck:
