### ISSUE TITLE
ignoring FromRequest implementation from `database` macro

### ISSUE THREAD

**Issue by muhammad-davatgar** [GREsau/okapi#116]
hello , so i'm currently using rocket v0.5.0rc.2 with  rocket_okapi 0.8.0-rc.2; i implement the `OpenApiFromRequest` trait manually for my diesel connection pool as instructed in your documentation; and as you know , the `database` macro implements the `FromRequest` trait automatically on my connection pool. but still `OpenApiFromRequest` is asking me to implement the `FromRequest` trait. i tried to implement `FromRequest` manually as well(beside the `database` macro) and as expected i got an error about conflicting implementation of `FromRequest` trait. what could be causing this and what can i do ? thanks in advance

**Comment by muhammad-davatgar** [comment]
it was because of crate version's not being synced; i had to fork this crate and update its dependencies manually; anyone with same problem can do the same too; just have to wait until updates will be applied.

**Comment by marcustut** [comment]
Mind showing how you did that? Was having this issue when using `rocket_db_pools`

**Comment by muhammad-davatgar** [comment]
you just gotta make sure rocket_okapi and rocket_db_pools are pointing to the same version of Rocket, you can do so by changing their Cargo.toml files

**Comment by muhammad-davatgar** [comment]
> Mind showing how you did that? Was having this issue when using `rocket_db_pools`
you just gotta make sure rocket_okapi and rocket_db_pools are pointing to the same version of Rocket, you can do so by changing their Cargo.toml files
