### ISSUE TITLE
Incorrect openapi.json Generated for Response with Tuple

### ISSUE THREAD

**Issue by MicaiahReid** [GREsau/okapi#127]
Hi! I think I've found a bug with the generated `openapi.json` file when my rocket server has a response type with a tuple. I've slightly modified the baseline example [in the docs](https://docs.rs/rocket_okapi/0.8.0-rc.3/rocket_okapi/index.html#example) to change the `Response` type to return a struct containing a tuple:

```rust
use rocket::serde::json::Json;
use rocket::{get};
use rocket_okapi::swagger_ui::{make_swagger_ui, SwaggerUIConfig};
use rocket_okapi::{openapi, openapi_get_routes, JsonSchema};

#[derive(serde::Serialize, JsonSchema)]
struct Response {
    reply: (u64, u64),
}

#[openapi]
#[get("/")]
fn my_controller() -> Json<Response> {
    Json(Response { reply: (1, 1) })
}

fn get_docs() -> SwaggerUIConfig {
    SwaggerUIConfig {
        url: "/my_resource/openapi.json".to_string(),
        ..Default::default()
    }
}

fn main() {
    rocket::build()
        .mount("/my_resource", openapi_get_routes![my_controller])
        .mount("/swagger", make_swagger_ui(&get_docs()))
        .launch();
}
```

This generates the following `openapi.json` file:
```JSON
{
  "openapi": "3.0.0",
  "info": {
    "title": "test-swagger",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "/my_resource"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "operationId": "my_controller",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Response": {
        "type": "object",
        "required": [
          "reply"
        ],
        "properties": {
          "reply": {
            "type": "array",
            "items": [
              {
                "type": "integer",
                "format": "uint64",
                "minimum": 0.0
              },
              {
                "type": "integer",
                "format": "uint64",
                "minimum": 0.0
              }
            ],
            "maxItems": 2,
            "minItems": 2
          }
        }
      }
    }
  }
}
```

Whenever I import this to [editor.swagger.io](https://editor.swagger.io/), I get the following error:

```
Structural error at components.schemas.Response.properties.reply.items
should be object
Semantic error at components.schemas.Response.properties.reply.items
`items` must be an object
```

I believe that, for this tuple type of `(u64, u64)`, this:
```JSON
          "reply": {
            "type": "array",
            "items": [
              {
                "type": "integer",
                "format": "uint64",
                "minimum": 0.0
              },
              {
                "type": "integer",
                "format": "uint64",
                "minimum": 0.0
              }
            ],
            "maxItems": 2,
            "minItems": 2
          }
```

should have actually been generated as
```JSON
          "reply": {
            "type": "array",
            "items": {
                "type": "integer",
                "format": "uint64",
                "minimum": 0.0
            },
            "maxItems": 2,
            "minItems": 2
          }
```

Is this a bug with the spec generation? Or is there something I'm doing wrong?

Thanks for the awesome tool and all of the work y'all are doing!

**Comment by ralpha** [comment]
Quickly checked. I'm not sure, but think this is a bug yes: 
> The value of "items" MUST be a valid JSON Schema.
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-10.3.1.2

This does not say list/array of JSON Schema(s).

Maybe `prefixItems` https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-10.3.1.1 Should be used instead. But will have to read up on it.

But this again is something in Schemars (different spec from OpenAPI spec), I know it is confusing and they are closely related in this case. So open issue in Schemars too https://github.com/GREsau/schemars/issues.

You can link back and include this info so it can be resolved quicker.

**Comment by GREsau** [comment]
OpenAPI 3.0.X uses (an extension of) the [JSON Schema Specification Wright Draft 00](http://json-schema.org/), which allows "items" to be an array - see https://spec.openapis.org/oas/v3.0.0#schemaObject and https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.9

OpenAPI 3.1.0 uses the newer [JSON Schema Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-4.2.1), which schemars (and by extension, okapi) does not yet support.

So for OpenAPI 3.0.0, which is what okapi currently produces, I believe the existing behaviour is correct

**Comment by hackermondev** [comment]
@GREsau I'm not sure if the OpenAPI 3.0.0 specification has been updated since your comment, but what you've said isn't true.

In the OpenAPI 3.0.0 specification you linked (spec.openapis.org/oas/v3.0.0#schemaObject), it says `items` must be an object and NOT an array.

<img width="799" height="287" alt="Image" src="https://github.com/user-attachments/assets/04cbbec2-a2cd-46e8-b3c3-96a752c8c021" />

This issue should be reopened. When using a struct with a tuple field, the generated OpenAPI spec is not spec compliant and cannot be parsed by a majority of OpenAPI parsers.
