### ISSUE TITLE
Update rocket dependency to v0.5.0-rc.4

### ISSUE THREAD

**Issue by kikniknik** [GREsau/okapi#130]
Rocket [version 0.5.0-rc.4](https://github.com/SergioBenitez/Rocket/releases/tag/v0.5.0-rc.4) has been released. Can we update the dependency in rocket_okapi?

**Comment by ralpha** [comment]
MR created, will review and merge soon.
https://github.com/GREsau/okapi/pull/132

**Comment by ralpha** [comment]
MR was merged, will be include in next release. Rocket v0.5 will be (as that has come out in the meanwhile)
