### ISSUE TITLE
Not possible to add custom schema responses anymore

### ISSUE THREAD

**Issue by johnlepikhin** [GREsau/okapi#14]
util.rs → add_schema_response() became private with [this commit](https://github.com/GREsau/okapi/commit/a1ee442545cd983b09b3d0fff21fbd84df6c687a#diff-0b2d36caa75a07bf3a3061ec0519f392R69). What's the reason doing so?

I used it to implement OpenApiResponder for my types which are serialized to Json in a custom way.

**Comment by GREsau** [comment]
Whoops, my bad...

I'd like to replace those functions at some point, probably with some sort of builder interface - but they should really be kept around until there's some sort of replacement.

I'll re-public them and publish a new version to crates.io ASAP

**Comment by GREsau** [comment]
Fixed in [rocket_okapi v0.3.5](https://crates.io/crates/rocket_okapi/0.3.5)
