### ISSUE TITLE
[FEATURE]: Support for Validated<T> implementation .

### ISSUE THREAD

**Issue by saeedtabrizi** [GREsau/okapi#142]
Hi all , 
Recently I had an issue with okapi integration with [rocket_validation](https://github.com/somehowchris/rocket-validation) `Validated` .
Is there any plan to implement Validated struct ? on the other please let me have a workaround to support validation in my project . 

Thanks

**Comment by saeedtabrizi** [comment]
When I try to implement this method in my project
```
impl<'r, T: JsonSchema + Deserialize<'r>> OpenApiFromData<'r> for Validated<T> {
    fn request_body(gen: &mut OpenApiGenerator)  {
        Json::request_body(gen)
    }
}
```

 I see the following error :
`
only traits defined in the current crate can be implemented for types defined outside of the crate
define and implement a trait or new type insteadrustc
sample.rs(26, 67): `Validated` is not defined in the current crate
`
what should I do to and is there any workaround to solve this issue ?

**Comment by ralpha** [comment]
See my comment on [#143](https://github.com/GREsau/okapi/pull/143#issuecomment-2081614043)
