### ISSUE TITLE
Responding with statuses other than 201, 202, 400 and 404

### ISSUE THREAD

**Issue by xylix** [GREsau/okapi#15]
Reading through the code, it seems like okapi only implements the aforementioned status codes in response schema generation. (https://github.com/GREsau/okapi/blob/master/rocket-okapi/src/response/responder_impls.rs ). Are there plans / interest to add full support for the entire range of possible status messages (e.g. probably adding a responder impl for [rocket::http::Status](https://docs.rs/rocket/0.4.2/rocket/http/struct.Status.html).

I tried implementing something but my macro skills aren't really up to par, and it isn't compiling. (https://github.com/GREsau/okapi/compare/master...xylix:extend-status-code-support )

I could also be misreading Rocket's status classes, but am unsure in what way.

**Comment by GREsau** [comment]
Okapi implements support for all status codes defined in [`rocket::response::status` in rocket 0.4.2](https://docs.rs/rocket/0.4.2/rocket/response/status/index.html). [Rocket 0.4.3 added a few more](https://docs.rs/rocket/0.4.3/rocket/response/status/index.html) (Conflict, Forbidden, NoContent, Unauthorized), which I can and will add support for.

Supporting `rocket::http::Status` (and `rocket::response::status::Custom`) usefully in Okapi would be very tricky, as the type itself contains no useful information about an exact status code - only an instance of that type knows the status code. For example:
```rust
#[get("/example1/<is_ok>")]
fn example1(is_ok: bool) -> Status {
    if is_ok {
        Status::Ok
    } else {
        Status::BadRequest
    }
}

#[get("/example2/<code>")]
fn example2(code: u16) -> Status {
    Status::from_code(code).unwrap_or(Status::NotFound)
}
```

The only way Okapi could determine the possible status codes for example1 would be to "look inside" the function body and scan for things that look like a return value with a discernible status code. This is probably possible, but I think it would be both difficult to implement and unreliable. And example2 could return pretty much any status code, so I'm not sure what Okapi could do in that situation.

**Comment by GREsau** [comment]
Would could work is if the `#[openapi]` attribute allowed you to explicitly specify the possible response codes - this could look something like:
```rust
#[openapi(response = 200)]
#[openapi(response = 400)]
#[get("/example1/<is_ok>")]
fn example1(is_ok: bool) -> Status {
    if is_ok {
        Status::Ok
    } else {
        Status::BadRequest
    }
}
```

**Comment by GREsau** [comment]
Support for rocket 0.4.3's new status codes in `rocket::response::status` is now implemented and available on crates.io in v0.4.0

**Comment by xylix** [comment]
Sounds great. I can only see up to version 0.3.0 on creates io though? (https://crates.io/crates/okapi )

**Comment by GREsau** [comment]
Whoops, that's weird, I could have sworn I published it to crates.io...

It's definitely done now:
https://crates.io/crates/okapi/0.4.0
https://crates.io/crates/rocket_okapi/0.4.0

**Comment by xylix** [comment]
Great, checking it out. Closing this since those implementations effectively fix the original issue.

**Comment by somehowchris** [comment]
Any chance of having it for `rocket::http::Status`? Currently the only thing holding me back

**Comment by ralpha** [comment]
> Any chance of having it for `rocket::http::Status`? Currently the only thing holding me back

This has been added and will be fixed in next release.
For more info see: https://github.com/GREsau/okapi/issues/20#issuecomment-916254590
