### ISSUE TITLE
Visibility of routes

### ISSUE THREAD

**Issue by ThouCheese** [GREsau/okapi#2]
Where a route is declared as a `pub fn`, Rocket creates a handlers that is also declared as `pub fn`. Currently, marking a route with `#[openapi] ` sets the route to private, making it impossible to generate documentation for routes that exists in another module.

**Comment by HerbLuo** [comment]
the same error i catched, 
and just for working 
1. in your `libraries/rocket-okapi-codegen/src/openapi_attr/mod.rs`, 
```rust
- fn #fn_name
+ pub fn #fn_name(
  gen: &mut ::rocket_okapi::gen::OpenApiGenerator,
   op_id: String,
) -> ::rocket_okapi::Result<()> {
```
2. delete the `target` folder, then rebuild the project.

**Comment by ThouCheese** [comment]
That you for the quick reply! This solved my issue.

**Comment by GREsau** [comment]
Good catch! I'm uploading rocket_okapi v0.1.1 to cargo which should have this fix
