### ISSUE TITLE
Result types should show example for Ok variant by default

### ISSUE THREAD

**Issue by TotalKrill** [GREsau/okapi#22]
As stated, it would be very nice if the examples generated by swagger ui would work for Result types by defaulting to the OK case. I would be willing to help with this if I got some pointers

**Comment by ralpha** [comment]
I'm not entirely sure what you mean by this. Could you provide an example or some more info?

I tried implementing a `Result` for a response type but that seems to work find in both the current master and the last version:
```rust
#[derive(Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase")]
struct User {
    user_id: u64,
    username: String,
    #[schemars(example = "example_email")]
    email: Option<String>,
    extra: Result<String, u8>,
}
```
![Screenshot from 2021-09-12 23-20-18](https://user-images.githubusercontent.com/2608639/133003140-f7bacc6b-4288-4dd7-b413-dac19562cc92.png)
![Screenshot from 2021-09-12 23-20-08](https://user-images.githubusercontent.com/2608639/133003141-705c04b0-5b45-4200-8897-822b5c7257b7.png)
![Screenshot from 2021-09-12 23-19-27](https://user-images.githubusercontent.com/2608639/133003142-bf1b0c56-87a6-4134-934d-c775f1d0db87.png)
![Screenshot from 2021-09-12 23-19-12](https://user-images.githubusercontent.com/2608639/133003143-38c1ad5b-e9a0-42f8-bf02-1d5979bf088f.png)

I'm not a big fan of the `Ok` casing (would like to see `ok` and `err`), but this an issue for Schemars. (see: https://github.com/GREsau/schemars/blob/55b860428e4526ef34886cb877af58256de6b046/schemars/src/json_schema_impls/core.rs#L78 )
@GREsau maybe you can take account the Serde `rename_all` or add a setting for this in `SchemaSettings`. But this is also a VERY small issue.

**Comment by TotalKrill** [comment]
I think this actually has been fixed then :) At this time I think I was using schemars 0.7 maybe, feel free to close this issue
