### ISSUE TITLE
Documenting query params

### ISSUE THREAD

**Issue by ThouCheese** [GREsau/okapi#25]
I'd like to use Okapi to document the query params in my Rocket `Route`. If I do the following:
```rust
#[openapi]
#[get("/?<id>")]
fn get_by_id(id: i32) -> String {
    format!("got {}", id)
}
```
then the resulting swagger has an empty `Parameters` section. I have tried switching to a form (which admittedly would make more sense because it allows you to add doc comments):
```rust
#[openapi]
#[derive(FromForm, JsonSchema)]
struct Query {
    /// This is the id that we will format very nicely for you.
    id: i32,
}

#[openapi]
#[get("/?<query..>)]
fn get_by_id(query: Query) -> String {
    format!("got {}", query.id)
}
```
This however yields the same results. Are query params not yet supported?

**Comment by ralpha** [comment]
Looked into this a bit more and looks like it is not implemented.

The parameters are added here: 
https://github.com/GREsau/okapi/blob/9807408fc1b0923c63c822920cea992ecf25318f/rocket-okapi-codegen/src/openapi_attr/mod.rs#L74

It calls this function:
https://github.com/GREsau/okapi/blob/9807408fc1b0923c63c822920cea992ecf25318f/rocket-okapi-codegen/src/openapi_attr/route_attr.rs#L17

It returns a list/iterator of all the parameters. To get the arguments it calls [`origin.segments()`](https://docs.rs/rocket/0.4.4/rocket/http/uri/struct.Origin.html#method.segments) from Rocket.
> Returns an iterator over the segments of the path in this URI. Skips empty segments.

So yes it only looks at the path. Not the Query parameters.
So to implement this we need to get `origin.query()` split that over all the elements so `.split('&')`. (or something similar)
But we have to do some more filtering for the cases where have fixed query parameter. For example: `#[get("/hello?wave&<name>")]` and what about parameters with no values? Like the `wave` in the example here.

Starting of for implementation:
```rust
pub fn query_params(&self) -> impl Iterator<Item = &str> {
    let mut query_params: Vec<&str> = vec![];
    if let Some(query) = self.origin.query(){
        query_params = query.split('&').collect();
        query_params = query_params.into_iter().filter_map(|s| {
            if s.starts_with('<') && s.ends_with('>') && !s.ends_with("..>") {
                Some(&s[1..s.len() - 1])
            } else {
                None
            }
        }).collect();
    }
    query_params.into_iter()
}
```
But this then has to integrate with the rest in `mod.rs`.

I'm not implementing this right now. But this would definitely be a nice addition. Maybe this helps you if you want to add support for this. I might implement it when I am going to need it in the future, but currently working on some other stuff.

**Comment by ralpha** [comment]
I would like to add to this that when a route with and one withouth a query parameter exist okapi will not handle this and panic the program.

```rust
#[openapi]
#[get("/coordinates")]
pub fn list_coordinates(){}

#[openapi]
#[get("/coordinates?<region_id>")]
pub fn list_coordinates_with_query(){}
```

```
thread 'main' panicked at 'An OpenAPI operation has already been added for 
GET /coordinates', rocket_okapi/src/gen.rs:39:17
```

For now you can solve this by using: `#[openapi(skip)]` instead of `#[openapi]` on one of the api calls.

**Comment by ralpha** [comment]
@ThouCheese implemented this in my pull request. So you can test it out in there if you like.
If anything is not working, let me know. But did quite a few tests now (with basic types) and seem to work fine in all cases.
Enjoy :smile:
