### ISSUE TITLE
Adding tags to resources

### ISSUE THREAD

**Issue by mattdowdell** [GREsau/okapi#35]
I couldn't see if this was supported in the docs, but what I'd like to do it add tags to resources to group them together, as demonstrated on https://swagger.io/docs/specification/grouping-operations-with-tags/.

One possible way to support this would be to add an attribute to `openapi`:

```rust
#[openapi(tag="example")]
#[get("/")]
fn example() -> status::NoContent
    unimplemented!()
}
```

From there, you could have a trait along the lines of the following:

```rust
pub trait OpenApiTag {
    fn tag(gen: &mut OpenApiGenerator) -> OpenApiTag;
}
```

Plus some code to stitch it together as I can't currently see a way for the generator to add tags.

**Comment by Type1J** [comment]
Hello @mattdowdell , I need this, too. I'm going to make a PR, but I'm using the async branch that hasn't been merged, yet.

**Comment by Type1J** [comment]
@mattdowdell : I'm not sure what you were talking about with the `trait`, but the `#[openapi(tag = "example")]` syntax should work. You can also add multiple tags.

**Comment by mattdowdell** [comment]
> I'm not sure what you were talking about with the trait

It's been long enough that I don't entirely recall. My best guess is to enable adding some sort of metadata into the tag (given that tags are more than their immediate label/name when rendered in the openapi/swagger explorer). I suspect the suggestion was inspired by a similar existing construct, but I forget what.

**Comment by raffomania** [comment]
I think this is now supported, see [the json-web-api example](https://github.com/GREsau/okapi/blob/master/examples/json-web-api/src/main.rs) on how to do it :)

**Comment by ralpha** [comment]
This has been added in version `rocket-okapi 0.7.0-alpha-1`.
