### ISSUE TITLE
Uuid in Parameter

### ISSUE THREAD

**Issue by genofire** [GREsau/okapi#38]
I got it nearly compiling with #29 and the rocket master ;)

But i got still an error on Uuid in parameter:
```
error[E0277]: the trait bound `rocket_contrib::uuid::Uuid: OpenApiFromParam<'_>` is not satisfied
  --> src/api/auth.rs:29:1
   |
29 | #[openapi]
   | ^^^^^^^^^^ the trait `OpenApiFromParam<'_>` is not implemented for `rocket_contrib::uuid::Uuid`
   |
   = note: required by `path_parameter`
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by wh75er** [comment]
@genofire did you solve your issue?

**Comment by genofire** [comment]
Nope .. but also not try it again

**Comment by ralpha** [comment]
This should be added to:
https://github.com/GREsau/okapi/blob/master/rocket-okapi/src/request/from_param_impls.rs

You should be able to add this with something like this
```rust
impl<'r> OpenApiFromParam<'r> for rocket_contrib::uuid::Uuid {
    fn path_parameter(gen: &mut OpenApiGenerator, name: String) -> Result {
        let schema = gen.json_schema::<rocket_contrib::uuid::Uuid>();
        Ok(Parameter {
            name,
            location: "path".to_owned(),
            description: None,
            required: true,
            deprecated: false,
            allow_empty_value: false,
            value: ParameterValue::Schema {
                style: None,
                explode: None,
                allow_reserved: false,
                schema,
                example: None,
                examples: None,
            },
            extensions: Default::default(),
        })
    }
}
```

Or maybe just:
```rust
impl_from_param!(rocket_contrib::uuid::Uuid);
```
But this should be under a feature flag, so people don't NEED to have rocket_contrib.

Don't have the time to do this atm, but maybe this helps someone make a PR.

**Comment by zeburek** [comment]
@genofire why not to use uuid::Uuid?

**Comment by raffomania** [comment]
@ralpha @GREsau I have implemented this in our application and would be willing to contribute it upstream. Would you be open to reviewing a PR from me?

**Comment by ralpha** [comment]
@raffomania I don't have any rights in this repo, but I can check a PR if you want to.
I still depend on @GREsau for the actual merge.
So yes you can make a PR, but be prepared that it might take some time before it gets merged.

**Comment by raffomania** [comment]
@ralpha Thanks for the offer to review. I've opened a PR at the rocket 0.5 fork we are currently using for our project, hoping that it will eventually get merged here. I'd be happy to see a review from you there.

**Comment by ralpha** [comment]
Hey @raffomania I'm currently fairly busy, but I have not forgotten about this. Just do not have much time at the moment to review it in depth. I'm also not familiar yet with the fork you committed the changes to, so would have to see how and if that would effect the change.

I just have taken a look very short look at the code for things that stand out and suggested some minor changes.
I'll take a better look when I have a bit more time, but it might be a week or 2-3. (sorry)
