### ISSUE TITLE
PathBuf parameters are not supported

### ISSUE THREAD

**Issue by snaggen** [GREsau/okapi#41]
I have a function where I take an input path like this:
```
#[openapi]
#[get("/<path..>")]
fn info(path: PathBuf, session: State<Session>) -> String {
    format!("info {:?}", path)
}

```
In the swagger ui, that is displayed as
![bild](https://user-images.githubusercontent.com/6420639/111453334-c25dfd00-8713-11eb-9472-bcf9ce932e96.png)

So there is no parameter listed. 

Note, this is with the following versions:
rocket = "0.4.7"
rocket_okapi = "0.6.0-alpha-1"
schemars = "0.7"
okapi = { version = "0.5.0-alpha-1", features = ["derive_json_schema"] }

**Comment by snaggen** [comment]
Just want to clarify this is not only PathBuf, but all <variable..>  ie. FromSegment trait variables

**Comment by ralpha** [comment]
`FromSegment` was not implemented at all. There where some things set up, but not finished.
The next update will have full support for this.
