### ISSUE TITLE
Support Rocket 0.5

### ISSUE THREAD

**Issue by williamdes** [GREsau/okapi#45]
Hi !
Rocket has released 0.5 in RC-1, can you support it ?

I had to disable okapi because Rocket 0.5 support stable channel of Rust and using actual version of this crate supports only previous Rocket and so it requires rust nightly

See my migration where I had to disable okapi: https://github.com/mountains/permafrost/commit/e7b5476e6ccd87a326c4fcc707c99d855787f4bd

**Comment by olback** [comment]
See #42.

Looks like we're just waiting for @GREsau to approve and merge.

**Comment by GREsau** [comment]
Thanks to the efforts of community members in #42, this is now published to crates.io as [0.7.0-alpha-1](https://crates.io/crates/rocket-okapi/0.7.0-alpha-1)! 🚀🚀🚀
