### ISSUE TITLE
Allow passing schema generation settings to okapi

### ISSUE THREAD

**Issue by raffomania** [GREsau/okapi#48]
The `RemoveRefSiblings` visitor breaks the openapi dart client generator (see https://github.com/OpenAPITools/openapi-generator/issues/9443) and we'd like to remove it when generating our openapi spec.

I know this is already on the list in the README, but  I think it would be good to track and discuss this feature here.

**Comment by ralpha** [comment]
I'm not entirely sure what you mean, but if it is:
Expose the [`SchemaSettings`](https://docs.rs/schemars/0.8.3/schemars/gen/struct.SchemaSettings.html)
so they can be set from okapi/rocket-okapi, then this is coming soon.

If the thing above does not solve your problem, let me know so I can add the setting.
But from the looks of it this is part of the `openapi.json -> components -> schemas` that is part of [`schemars`](https://github.com/GREsau/schemars). So unless schemars exposes that settings that has to be handled there.

Next up I'll start working on adding some settings that can be customized from rocket-okapi, so let me know soon what settings you need.

**Comment by raffomania** [comment]
Yes, setting the `SchemaSettings` is exactly what we need :) thanks a lot!

**Comment by ralpha** [comment]
This had been added in https://github.com/GREsau/okapi/commit/be2e3dd7f14fb1966e0cc9b295a9a5d201cc54a2
Also see the example: https://github.com/GREsau/okapi/blob/master/examples/custom_schema/src/main.rs#L48:L55

So this will also be added in the next release.
