### ISSUE TITLE
The trait OpenApiResponder is not implemented for rocket::response::content::Plain

### ISSUE THREAD

**Issue by zlnpgtdtfezf** [GREsau/okapi#5]
Given a route function which uses `rocket::response::content::*` wrappers to specify the returned content type okapi fails bc the responder is not implemented on the wrapper types.

```
the trait `rocket_okapi::response::OpenApiResponder<'_>` is not implemented for `rocket::response::content::Plain<std::string::String>`
```

**Comment by GREsau** [comment]
This is now published to crates.io as rocket_okapi v0.3.1 https://crates.io/crates/rocket_okapi/0.3.1
