### ISSUE TITLE
Add 'discriminator' property on anyOf relations for use with openapi-generate

### ISSUE THREAD

**Issue by Tails** [GREsau/okapi#50]
With the default settings, unions are rendered using the 'anyOf' relation, which is fine:

````yaml
TreeModel:
      anyOf:
        - $ref: '#/components/schemas/ScoreTree'
        - $ref: '#/components/schemas/SongTree'
        - $ref: '#/components/schemas/PartTree'
        - ... etc
 ````

But when you want to use the OpenAPI generator to generate client code, the enum declaration needs (at least >= openapi-generator v5.0.0) a 'discriminator' property: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

This seems to correlate with serde's ````#[serde(tag = "type")]```` [serialization option](https://serde.rs/container-attrs.html#tag) for enums.

**Edit:** seems to be more related to Schemars. Pre-existing issue: https://github.com/GREsau/schemars/issues/39

**Comment by ralpha** [comment]
Yes this looks like Schemars need to fix this. If something needs fixing here, let me know or reopen this issue.
I'll close the issue here as this will be fixed in GREsau/schemars#39.
