### ISSUE TITLE
Query parameters show up as camelCase but rocket expects snake_case

### ISSUE THREAD

**Issue by raffomania** [GREsau/okapi#55]
Given the following handler:
```rust
#[openapi(tag = "users")]
#[get("/?<page>&<sort_key>&<sort_direction>")]
pub async fn list_users(
    page: Option<usize>,
    sort_key: Option<UserSortKey>,
    sort_direction: Option<SortDirection>,
) -> Result<Json<Vec<User>>, AppError> { }
```

The resulting spec contains the following `parameters` array:
```json
"parameters": [
  {
    "name": "page",
    "in": "query",
    "schema": {
      "type": "integer",
      "format": "uint",
      "minimum": 0.0
    }
  },
  {
    "name": "SortKey",
    "in": "query",
    "schema": {
      "$ref": "#/components/schemas/UserSortKey"
    }
  },
  {
    "name": "sortDirection",
    "in": "query",
    "schema": {
      "$ref": "#/components/schemas/SortDirection"
    }
  }
],
```

The `name`s in the spec are all written in camelCase, however rocket expects the keys of the query params to be written in snake_case.
Can we adjust okapi to mirror the format rocket expects?

**Comment by ralpha** [comment]
I tried reproducing this issue but could not do so.
I think you might have a problem with your `OpenApiFromFormField` implementation for `SortKey`.
Make sure that the `Parameter.name` field is set correctly.

Here is the one I created to this this:
```rust
#[derive(Serialize, Deserialize, JsonSchema, FromForm)]
struct UserSortKey {
    sort_by: String,
}

use rocket_okapi::request::OpenApiFromFormField;
use rocket_okapi::gen::OpenApiGenerator;
use okapi::openapi3::{Parameter, ParameterValue};

impl<'r> OpenApiFromFormField<'r> for UserSortKey {
    fn form_parameter(gen: &mut OpenApiGenerator, name: String, required: bool) -> rocket_okapi::Result<Parameter> {
        let schema = gen.json_schema::<String>();
        Ok(Parameter {
            name,
            location: "query".to_owned(),
            description: None,
            required,
            deprecated: false,
            allow_empty_value: false,
            value: ParameterValue::Schema {
                style: None,
                explode: None,
                allow_reserved: false,
                schema,
                example: None,
                examples: None,
            },
            extensions: okapi::Map::default(),
        })
    }
}
```

If you are sure this `name` field is set correctly could you please sent your `UserSortKey` or `SortDirection` struct. So I know how you structured them. (Also let me know what version of `rocket_okapi` you are using)

I also checked in the current master branch version and found some other problems that I'll fix, but they are unrelated to the casing of the names.
Note that the code above would be redundant in future releases. Now `rocket_okapi` will automatically implement `OpenApiFromFormField` (using generics).

Let me know if there is something I can do to resolve this.

**Comment by raffomania** [comment]
Of course, I completely overlooked our custom implementation when debugging this. Sorry for the time it took you, though I'm glad you found other problems in the process :)
