### ISSUE TITLE
okapi_add_operation_for_ visible in my projects documentation

### ISSUE THREAD

**Issue by snaggen** [GREsau/okapi#69]
When i generate rustdoc for my project, I find okapi_add_operation_for_<real function> functions in the documentation, which is a bit confusing since these are not visible in the project source anywhere (since I assume they are derived from the okapi macros). 
I assume it would be good if these functions could be generated with #[doc(hidden)] somehow...

**Comment by ralpha** [comment]
Thanks for the issue, good catch.
Fixed in master, will be included in next release.
