### ISSUE TITLE
Unable to deserialize SecurityScheme

### ISSUE THREAD

**Issue by brendo-m** [GREsau/okapi#74]
I've run into an issue beyond my Rust knowledge when trying to deserialize a `SecurityScheme`. This test will repro.

```
#[test]
fn test_deser_security_scheme() -> Result<(), Box<dyn std::error::Error>> {
    let raw = r#"{
        "type": "apiKey",
        "description": "AWS Signature Version 4 authentication",
        "name": "Authorization",
        "in": "header",
        "x-amazon-apigateway-authtype": "awsSigv4" 
    }"#;

    let deser: openapi3::SecurityScheme = serde_json::from_str(raw)?;

    assert_eq!(
        deser,
        openapi3::SecurityScheme {
            schema_type: "apiKey".to_string(),
            description: Some("AWS Signature Version 4 authentication".to_string()),
            data: openapi3::SecuritySchemeData::ApiKey {
                location: "header".to_string(),
                name: "Authorization".to_string(),
            },
            extensions: okapi::Map::new() // should have x-amazon-apigateway-authtype
        }
    );
    Ok(())
}
```

Deserializing fails with `Error: Error("missing field `type`", line: 7, column: 5)`. `type` is definitely there though. It has to have something to with https://github.com/GREsau/okapi/pull/56/files#diff-fb72987bae6646074514b23cd41d13a4d1b851455b9bf21084a32668fd729196 but I'm not sure what.

**Comment by brendo-m** [comment]
Found this but there was no resolution: https://github.com/serde-rs/json/issues/361

**Comment by brendo-m** [comment]
Ah just caught that I am still using 0.4.0, will try updating

**Comment by brendo-m** [comment]
Yeah that was it, sorry for the false alarm.

Is there a timeline for the next release to crates.io?

**Comment by ralpha** [comment]
This should have/has been solved in a previous release https://crates.io/crates/okapi/0.7.0-rc.1
