### ISSUE TITLE
How to add a description for the route parameters 

### ISSUE THREAD

**Issue by lrodriguez14** [GREsau/okapi#76]
Hello,

I want to know if there is any way to add a description to the route parameters?

For example:
```
/// # Get user
///
/// Returns a single user by ID.
#[openapi(tag = "Users")]
#[get("/user/<id>")]
```
How can I add a little description for <id>? 
As we can see in the image the description is empty
![image](https://user-images.githubusercontent.com/61153030/156824657-e083038e-4f0e-40d2-8b60-b476b899af34.png)

Thanks!

**Comment by ralpha** [comment]
Create a custom type (so not just `u64`) and implement `JsonSchema` trait for it.

example:
```rust
#[derive(Serialize, Deserialize, JsonSchema, FromForm)]
struct Post {
    /// The unique identifier for the post.
    post_id: u64,
}
```

Example code: https://github.com/GREsau/okapi/blob/master/examples/json-web-api/src/main.rs#L74-L82

There does not currently exist a macro or something so do this easier.

**Comment by ralpha** [comment]
No response and no further action seems to be needed. Closing issue.

**Comment by jiangxiaoqiang** [comment]
I am facing the same issue. is it possible to support the easier way to do this issue?

**Comment by ralpha** [comment]
> I am facing the same issue. is it possible to support the easier way to do this issue?

No, currently there is no other (easier) way of solving this.
Otherwise we would have to create a macro that basically does the same. But this had not been created up until now.
