### ISSUE TITLE
Support for request guards

### ISSUE THREAD

**Issue by Geigerkind** [GREsau/okapi#8]
Hey!
First of all: Amazing crate! Thank you very much for this!

I am using request guards to add authentication to my application. This requires the user to add the Authorization header to a number of requests.

I would like to specify this in the API documentation.

An example function can look like this:
```
#[openapi]
#[get("/get")]
pub fn get_account_information(me: State<Account>, auth: Authenticate) -> Result<Json<AccountInformation>, Failure>
{
  me.get(auth.0)
    .and_then(|acc_info| Ok(Json(acc_info)))
}
```
The authentication guard returns 401 if the token does not match any user and adds the header requirement to the request.

**Comment by Geigerkind** [comment]
nvm

**Comment by Geigerkind** [comment]
FromRequest is missing

**Comment by Geigerkind** [comment]
Note: For headers like "Authorization", a security component needs to be added instead.

**Comment by ralpha** [comment]
Added support for Request Guards in #56.
