### ISSUE TITLE
rocket_okapi v0.8.0-rc.1 failing to build after rocket v0.5.0-rc.2 released

### ISSUE THREAD

**Issue by pintariching** [GREsau/okapi#90]
After `rocket v0.5.0-rc.2` released, selecting the version `0.5.0-rc.1` somehow selects the `rc.2` version and all sorts of problems start coming up during the compile.

This can be fixed by adding a fixed rocket version like `"=0.5.0-rc.1"` to the `cargo.toml` in the `rocket-okapi` and `rocket-okapi-codegen` project as a workaround until the new rocket version gets supported.

**Comment by ralpha** [comment]
Fixed in branch, see #91
