### ISSUE TITLE
Updated Swagger and Rapidocs, request testing

### ISSUE THREAD

**Issue by ralpha** [GREsau/okapi#98]
Hello Okapi users.

I updated the crate to Rocket v0.5.0-rc.2 and updated Rapidoc and Swagger UI. (the versions included in the lib)
It would be wonderful it there where some people that can see if everything still works in there environment before I create a release.
Thanks

Also if you have public documentation (API docs) for your project and want to be featured in the Readme as an example, let me know below (please explicitly state whether I can use it in the Readme). I think both open source and commercial are okay, of course within reason.
Even if you don't want to be featured, I think it would still be cool to see what other people have created.

@svenstaro @ThouCheese @hardliner66 @olback @NCrashed @Glitchy-Tozier

**Comment by svenstaro** [comment]
Seems to work well on our fairly complex application.

**Comment by Glitchy-Tozier** [comment]
Seems to work well on my fairly [simple application](https://gitlab.com/Glitchy-Tozier/time.vote).
You can use screenshots of the API if you manage to set up the project (requires `npm` & postgreSQL) :wink: 

The client-side part of the project is still in the beginning phases, but the back-end should work and be decently documented.
(If you find anything that should be improved, hit me up!)

**Comment by arturh85** [comment]
works for my simple application as well, thank you👍

**Comment by ralpha** [comment]
New versions have been published to crates.io
https://crates.io/crates/rocket_okapi/0.8.0-rc.2
(best update dependencies to crates.io version instead of `master` branch)
```toml
rocket_okapi = { version = "0.8.0-rc.2", features = ["..."]}
```
All feature flags can be found here: https://github.com/GREsau/okapi/#feature-flags
